version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - dscpinheiro
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - dscpinheiro
