version: "3.7"

services:
  api:
    build:
      context: .
      target: runtime
    ports:
      - 5000:8080
    depends_on:
      - db
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - API_DB_CONNECTION=Host=db;Database=mydatabase;Username=myappuser;Password=mypassword
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8080/hc || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=mypassword

networks:
  backend:

volumes:
  db-data:
