version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - docker build --target testrunner -t unittests .
      - docker run --name testrunner unittests
      - EXIT_CODE=$(docker inspect testrunner --format='{{.State.ExitCode}}')
      - exit $EXIT_CODE
