version: 0.2

env:
  variables:
    BUILD_CONFIG: Release
    ASPNETCORE_ENVIRONMENT: CI

phases:
  install:
    commands:
      - dotnet --info
  pre_build:
    commands:
      - echo Test started on `date`
      - dotnet restore
  build:
    commands:
      - dotnet build -c $BUILD_CONFIG
      - dotnet test -c $BUILD_CONFIG --logger trx --results-directory ./testresults
  post_build:
    commands:
      - echo Test completed on `date`
reports:
  TestResults:
    files:
      - '**/*'
    base-directory: './testresults'
    file-format: VisualStudioTrx
