version: 0.2

env:
  variables:
    BUILD_CONFIG: Release

phases:
  install:
    runtime-versions:
      dotnet: 2.2
  pre_build:
    commands:
      - echo Test started on `date`
      - dotnet restore
  build:
    commands:
      - dotnet build -c $BUILD_CONFIG
      - dotnet test -c $BUILD_CONFIG
  post_build:
    commands:
      - echo Test completed on `date`
