version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - cd Messages.Benchmark
      - dotnet run -c Release
artifacts:
  files:
    - '**/*'
  base-directory: './Messages.Benchmark/BenchmarkDotNet.Artifacts/results'
  name: benchmark-$(date +%Y-%m-%d)
