version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - cd Messages.Benchmark
      - dotnet run -c Release
artifacts:
  files:
    - 'Messages.Benchmark/BenchmarkDotNet.Artifacts/results/*'
  discard-paths: yes
  name: benchmark-$(date -u +%Y%m%d%H%M%S).zip
